import PDFDocument from 'pdfkit';
import { formatINR, formatDateTime, formatDate } from '../utils/format.js';

const COMPANY = process.env.COMPANY_NAME || 'Puro Soul';
const INK = '#0f172a';
const MUTED = '#64748b';
const ACCENT = '#185997'; // Puro Soul brand blue (purosoul.in)
const ACCENT_BG = '#eff6fc';
const ACCENT_BORDER = '#bcd8ef';
const LINE = '#e2e8f0';

function docToBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

function header(doc, title, subtitle) {
  doc.fillColor(ACCENT).font('Helvetica-Bold').fontSize(16).text(`${COMPANY} — Cash Collection`, 50, 50);
  doc.moveDown(0.2);
  doc.fillColor(INK).fontSize(13).text(title);
  if (subtitle) doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(subtitle);
  doc.moveTo(50, doc.y + 8).lineTo(545, doc.y + 8).strokeColor(LINE).stroke();
  doc.y += 18;
}

function footer(doc) {
  doc.fontSize(8).fillColor(MUTED);
  doc.text(
    `System generated by ${COMPANY} Cash Collection Verification • ${formatDateTime(new Date())} IST • No signature required`,
    50,
    790,
    { width: 495, align: 'center' }
  );
}

/** Single-collection receipt — attached to every verification email. */
export function receiptPdf(txn) {
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  header(doc, 'Collection Receipt', `Reference: ${txn.ref}`);

  const rows = [
    ['Party', txn.party?.name || '—'],
    ['Party mobile', txn.party?.mobile ? `+91 ${txn.party.mobile}` : '—'],
    ['Collected by (driver)', txn.driver?.name || '—'],
    ['Amount collected', formatINR(txn.amount)],
    ['Collected on', formatDateTime(txn.createdAt)],
    ['OTP verified at', formatDateTime(txn.verifiedAt)],
    ['Status', 'VERIFIED — acknowledged by party via OTP'],
  ];
  if (txn.notes) rows.push(['Notes', txn.notes]);

  let y = doc.y + 6;
  for (const [label, value] of rows) {
    doc.font('Helvetica').fontSize(10).fillColor(MUTED).text(label, 50, y, { width: 160 });
    doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text(value, 220, y, { width: 325 });
    y = Math.max(doc.y, y + 16) + 6;
    doc.moveTo(50, y - 3).lineTo(545, y - 3).strokeColor(LINE).stroke();
  }

  // Amount callout
  y += 14;
  doc.roundedRect(50, y, 495, 54, 6).fillAndStroke(ACCENT_BG, ACCENT_BORDER);
  doc.fillColor(ACCENT).font('Helvetica').fontSize(9).text('TOTAL CASH COLLECTED', 70, y + 10);
  doc.font('Helvetica-Bold').fontSize(20).text(formatINR(txn.amount), 70, y + 24);

  doc.fillColor(MUTED).font('Helvetica').fontSize(9);
  doc.text(
    'This receipt certifies that the party acknowledged the above cash collection by sharing the one-time password sent to their registered mobile number.',
    50,
    y + 74,
    { width: 495 }
  );

  footer(doc);
  return docToBuffer(doc);
}

const TABLE_COLS = [
  { key: 'date', label: 'Date', x: 50, w: 90 },
  { key: 'ref', label: 'Ref', x: 140, w: 65 },
  { key: 'party', label: 'Party', x: 205, w: 130 },
  { key: 'driver', label: 'Driver', x: 335, w: 100 },
  { key: 'amount', label: 'Amount', x: 435, w: 110, align: 'right' },
];

function tableHeader(doc, y) {
  doc.font('Helvetica-Bold').fontSize(9).fillColor(MUTED);
  for (const col of TABLE_COLS) doc.text(col.label.toUpperCase(), col.x, y, { width: col.w, align: col.align || 'left' });
  doc.moveTo(50, y + 14).lineTo(545, y + 14).strokeColor(LINE).stroke();
  return y + 20;
}

function ensureSpace(doc, y, needed = 60) {
  if (y > 780 - needed) {
    footer(doc);
    doc.addPage();
    return tableHeader(doc, 60);
  }
  return y;
}

/**
 * Multi-transaction report used by the Reports section exports.
 * report = { title, subtitle, groups: [{ label, breakdown?, rows: [{date,ref,party,driver,amount}], subtotal, count }], grandTotal, grandCount }
 */
export function reportPdf(report) {
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  header(doc, report.title, report.subtitle);

  // Summary band
  let y = doc.y + 4;
  doc.roundedRect(50, y, 495, 46, 6).fillAndStroke('#f8fafc', LINE);
  doc.fillColor(MUTED).font('Helvetica').fontSize(8).text('TOTAL VERIFIED COLLECTIONS', 70, y + 9);
  doc.fillColor(ACCENT).font('Helvetica-Bold').fontSize(16).text(formatINR(report.grandTotal), 70, y + 20);
  doc.fillColor(MUTED).font('Helvetica').fontSize(8).text('TRANSACTIONS', 400, y + 9);
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(16).text(String(report.grandCount), 400, y + 20);
  y += 62;

  y = tableHeader(doc, y);

  for (const group of report.groups) {
    y = ensureSpace(doc, y, 80);
    if (report.groups.length > 1 || group.label !== 'All transactions') {
      doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text(group.label, 50, y);
      y = doc.y + 4;
      if (group.breakdown) {
        doc.font('Helvetica').fontSize(8).fillColor(MUTED).text(group.breakdown, 50, y, { width: 495 });
        y = doc.y + 4;
      }
    }
    for (const row of group.rows) {
      y = ensureSpace(doc, y);
      doc.font('Helvetica').fontSize(9).fillColor(INK);
      doc.text(formatDate(row.date), TABLE_COLS[0].x, y, { width: TABLE_COLS[0].w });
      doc.text(row.ref, TABLE_COLS[1].x, y, { width: TABLE_COLS[1].w });
      doc.text(row.party, TABLE_COLS[2].x, y, { width: TABLE_COLS[2].w, ellipsis: true, height: 12 });
      doc.text(row.driver, TABLE_COLS[3].x, y, { width: TABLE_COLS[3].w, ellipsis: true, height: 12 });
      doc.text(formatINR(row.amount), TABLE_COLS[4].x, y, { width: TABLE_COLS[4].w, align: 'right' });
      y += 16;
    }
    // Group subtotal
    y = ensureSpace(doc, y);
    doc.moveTo(300, y).lineTo(545, y).strokeColor(LINE).stroke();
    y += 5;
    doc.font('Helvetica-Bold').fontSize(9).fillColor(INK);
    doc.text(`Subtotal (${group.count} txns)`, 300, y, { width: 130, align: 'right' });
    doc.text(formatINR(group.subtotal), 435, y, { width: 110, align: 'right' });
    y += 24;
  }

  y = ensureSpace(doc, y, 40);
  doc.moveTo(50, y).lineTo(545, y).strokeColor(INK).stroke();
  y += 8;
  doc.font('Helvetica-Bold').fontSize(11).fillColor(ACCENT);
  doc.text('GRAND TOTAL', 250, y, { width: 180, align: 'right' });
  doc.text(formatINR(report.grandTotal), 435, y, { width: 110, align: 'right' });

  footer(doc);
  return docToBuffer(doc);
}
