import PDFDocument from 'pdfkit';
import { formatINR, formatDateTime } from '../utils/format.js';

const COMPANY = process.env.COMPANY_NAME || 'Puro Soul';
const INK = '#0f172a';
const MUTED = '#64748b';
const ACCENT = '#185997'; // Puro Soul brand blue (purosoul.in)
const ACCENT_BG = '#eff6fc';
const ACCENT_BORDER = '#bcd8ef';
const LINE = '#e2e8f0';

function docToBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

function header(doc, title, subtitle) {
  doc.fillColor(ACCENT).font('Helvetica-Bold').fontSize(16).text(`${COMPANY} — Cash Collection`, 50, 50);
  doc.moveDown(0.2);
  doc.fillColor(INK).fontSize(13).text(title);
  if (subtitle) doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(subtitle);
  doc.moveTo(50, doc.y + 8).lineTo(545, doc.y + 8).strokeColor(LINE).stroke();
  doc.y += 18;
}

function footer(doc) {
  // The footer sits inside the bottom margin; lift the margin while writing it,
  // or pdfkit pushes the footer onto a page of its own.
  const bottom = doc.page.margins.bottom;
  doc.page.margins.bottom = 0;
  doc.fontSize(8).fillColor(MUTED);
  doc.text(
    `System generated by ${COMPANY} Cash Collection Verification • ${formatDateTime(new Date())} IST • No signature required`,
    50,
    790,
    { width: 495, align: 'center' }
  );
  doc.page.margins.bottom = bottom;
}

/** Single-collection receipt — attached to every verification email. */
export function receiptPdf(txn) {
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  header(doc, 'Collection Receipt', `Reference: ${txn.ref}`);

  const rows = [
    ['Party', txn.party?.name || '—'],
    // The number the OTP actually went to — not the party's current default,
    // which may have been switched after this collection was verified.
    ['Party mobile', txn.otpMobile || txn.party?.mobile ? `+91 ${txn.otpMobile || txn.party.mobile}` : '—'],
    ['Collected by (collector)', txn.collector?.name || '—'],
    ['Amount collected', formatINR(txn.amount)],
    ['Collected on', formatDateTime(txn.createdAt)],
    ['OTP verified at', formatDateTime(txn.verifiedAt)],
    ['Status', 'VERIFIED — acknowledged by party via OTP'],
  ];
  if (txn.notes) rows.push(['Notes', txn.notes]);

  let y = doc.y + 6;
  for (const [label, value] of rows) {
    doc.font('Helvetica').fontSize(10).fillColor(MUTED).text(label, 50, y, { width: 160 });
    doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text(value, 220, y, { width: 325 });
    y = Math.max(doc.y, y + 16) + 6;
    doc.moveTo(50, y - 3).lineTo(545, y - 3).strokeColor(LINE).stroke();
  }

  // Amount callout
  y += 14;
  doc.roundedRect(50, y, 495, 54, 6).fillAndStroke(ACCENT_BG, ACCENT_BORDER);
  doc.fillColor(ACCENT).font('Helvetica').fontSize(9).text('TOTAL CASH COLLECTED', 70, y + 10);
  doc.font('Helvetica-Bold').fontSize(20).text(formatINR(txn.amount), 70, y + 24);

  doc.fillColor(MUTED).font('Helvetica').fontSize(9);
  doc.text(
    'This receipt certifies that the party acknowledged the above cash collection by sharing the one-time password sent to their registered mobile number.',
    50,
    y + 74,
    { width: 495 }
  );

  footer(doc);
  return docToBuffer(doc);
}

/** Handover receipt — attached to the handover-verified email; lists each party's amount. */
export function handoverReceiptPdf(handover, collector, parties) {
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  header(doc, 'Cash Handover Receipt', `Reference: ${handover.ref}`);

  const receivedBy = handover.recipientDesignation
    ? `${handover.recipientName} — ${handover.recipientDesignation}`
    : handover.recipientName;
  const rows = [
    ['Handed over by (collector)', collector?.name || '—'],
    ['Received by', receivedBy],
    ['Collections handed over', String(handover.transactions.length)],
    ['OTP verified at', formatDateTime(handover.verifiedAt)],
    ['Status', 'VERIFIED — acknowledged by receiver via OTP'],
  ];
  if (handover.notes) rows.push(['Notes', handover.notes]);

  let y = doc.y + 6;
  for (const [label, value] of rows) {
    doc.font('Helvetica').fontSize(10).fillColor(MUTED).text(label, 50, y, { width: 160 });
    doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text(value, 220, y, { width: 325 });
    y = Math.max(doc.y, y + 16) + 6;
    doc.moveTo(50, y - 3).lineTo(545, y - 3).strokeColor(LINE).stroke();
  }

  // Party-wise breakdown of the cash handed over
  y += 14;
  doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text('Party-wise amounts', 50, y);
  y = doc.y + 6;
  doc.font('Helvetica-Bold').fontSize(9).fillColor(MUTED);
  doc.text('PARTY', 50, y, { width: 275 });
  doc.text('COLLECTIONS', 330, y, { width: 100, align: 'right' });
  doc.text('AMOUNT', 435, y, { width: 110, align: 'right' });
  doc.moveTo(50, y + 14).lineTo(545, y + 14).strokeColor(LINE).stroke();
  y += 20;
  for (const p of parties || []) {
    if (y > 720) {
      footer(doc);
      doc.addPage();
      y = 60;
    }
    doc.font('Helvetica').fontSize(9).fillColor(INK);
    doc.text(p.name, 50, y, { width: 275, ellipsis: true, height: 12 });
    doc.text(String(p.count), 330, y, { width: 100, align: 'right' });
    doc.text(formatINR(p.amount), 435, y, { width: 110, align: 'right' });
    y += 16;
  }

  if (y > 680) {
    footer(doc);
    doc.addPage();
    y = 60;
  }
  y += 8;
  doc.roundedRect(50, y, 495, 54, 6).fillAndStroke(ACCENT_BG, ACCENT_BORDER);
  doc.fillColor(ACCENT).font('Helvetica').fontSize(9).text('TOTAL CASH HANDED OVER', 70, y + 10);
  doc.font('Helvetica-Bold').fontSize(20).text(formatINR(handover.totalAmount), 70, y + 24);

  doc.fillColor(MUTED).font('Helvetica').fontSize(9);
  doc.text(
    'This receipt certifies that the receiver acknowledged taking custody of the above cash by sharing the one-time password sent to their registered mobile number.',
    50,
    y + 74,
    { width: 495 }
  );

  footer(doc);
  return docToBuffer(doc);
}

const TABLE_COLS = [
  { key: 'date', label: 'Date & time', x: 50, w: 115 },
  { key: 'ref', label: 'Ref', x: 165, w: 60 },
  { key: 'party', label: 'Party', x: 225, w: 120 },
  { key: 'collector', label: 'Collector', x: 345, w: 95 },
  { key: 'amount', label: 'Amount', x: 440, w: 105, align: 'right' },
];

function tableHeader(doc, y, cols = TABLE_COLS) {
  doc.font('Helvetica-Bold').fontSize(9).fillColor(MUTED);
  for (const col of cols) doc.text(col.label.toUpperCase(), col.x, y, { width: col.w, align: col.align || 'left' });
  doc.moveTo(50, y + 14).lineTo(545, y + 14).strokeColor(LINE).stroke();
  return y + 20;
}

function ensureSpace(doc, y, needed = 60, cols = TABLE_COLS) {
  if (y > 780 - needed) {
    footer(doc);
    doc.addPage();
    return tableHeader(doc, 60, cols);
  }
  return y;
}

/**
 * Multi-transaction report used by the Reports section exports.
 * report = { title, subtitle, groups: [{ label, breakdown?, rows: [{date,ref,party,collector,amount}], subtotal, count }], grandTotal, grandCount }
 */
export function reportPdf(report) {
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  header(doc, report.title, report.subtitle);

  // Column labels may be overridden per report type (e.g. handovers: party → "Received by").
  const cols = TABLE_COLS.map((c) => ({ ...c, label: report.colLabels?.[c.key] || c.label }));

  // Summary band
  let y = doc.y + 4;
  doc.roundedRect(50, y, 495, 46, 6).fillAndStroke('#f8fafc', LINE);
  doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(report.totalLabel || 'TOTAL VERIFIED COLLECTIONS', 70, y + 9);
  doc.fillColor(ACCENT).font('Helvetica-Bold').fontSize(16).text(formatINR(report.grandTotal), 70, y + 20);
  doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(report.countLabel || 'TRANSACTIONS', 400, y + 9);
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(16).text(String(report.grandCount), 400, y + 20);
  y += 62;

  y = tableHeader(doc, y, cols);

  for (const group of report.groups) {
    y = ensureSpace(doc, y, 80, cols);
    if (report.groups.length > 1 || group.label !== 'All transactions') {
      doc.font('Helvetica-Bold').fontSize(10).fillColor(INK).text(group.label, 50, y);
      y = doc.y + 4;
      if (group.breakdown) {
        doc.font('Helvetica').fontSize(8).fillColor(MUTED).text(group.breakdown, 50, y, { width: 495 });
        y = doc.y + 4;
      }
    }
    for (const row of group.rows) {
      y = ensureSpace(doc, y, 60, cols);
      doc.font('Helvetica').fontSize(9).fillColor(INK);
      doc.text(formatDateTime(row.date), TABLE_COLS[0].x, y, { width: TABLE_COLS[0].w, height: 12, ellipsis: true });
      doc.text(row.ref, TABLE_COLS[1].x, y, { width: TABLE_COLS[1].w });
      doc.text(row.party, TABLE_COLS[2].x, y, { width: TABLE_COLS[2].w, ellipsis: true, height: 12 });
      doc.text(row.collector, TABLE_COLS[3].x, y, { width: TABLE_COLS[3].w, ellipsis: true, height: 12 });
      doc.text(formatINR(row.amount), TABLE_COLS[4].x, y, { width: TABLE_COLS[4].w, align: 'right' });
      y += 16;
    }
    // Group subtotal
    y = ensureSpace(doc, y, 60, cols);
    doc.moveTo(300, y).lineTo(545, y).strokeColor(LINE).stroke();
    y += 5;
    doc.font('Helvetica-Bold').fontSize(9).fillColor(INK);
    doc.text(`Subtotal (${group.count} txns)`, 300, y, { width: 130, align: 'right' });
    doc.text(formatINR(group.subtotal), 435, y, { width: 110, align: 'right' });
    y += 24;
  }

  y = ensureSpace(doc, y, 40, cols);
  doc.moveTo(50, y).lineTo(545, y).strokeColor(INK).stroke();
  y += 8;
  doc.font('Helvetica-Bold').fontSize(11).fillColor(ACCENT);
  doc.text('GRAND TOTAL', 250, y, { width: 180, align: 'right' });
  doc.text(formatINR(report.grandTotal), 435, y, { width: 110, align: 'right' });

  footer(doc);
  return docToBuffer(doc);
}

// ------------------------------------------------------------------ events ---

const amountOnly = (n) => formatINR(n).replace('Rs. ', '');
const MINI_W = 227; // 80 mm — prints on a thermal roll and reads well when shared on a phone
const MINI_M = 14;

/** Customer-facing mini bill for one verified event sale. */
export function eventBillPdf(bill, event) {
  const lines = bill.lines || [];
  const height = 330 + lines.length * 26 + (bill.upiRef ? 12 : 0) + (event?.venue ? 12 : 0);
  const doc = new PDFDocument({ size: [MINI_W, height], margin: MINI_M, bufferPages: true });
  const W = MINI_W - 2 * MINI_M;
  let y = MINI_M + 4;

  const center = (text, size, font = 'Helvetica', color = INK) => {
    doc.font(font).fontSize(size).fillColor(color).text(text, MINI_M, y, { width: W, align: 'center' });
    y = doc.y + 2;
  };
  const rule = () => {
    y += 3;
    doc.moveTo(MINI_M, y).lineTo(MINI_W - MINI_M, y).dash(2, { space: 2 }).strokeColor('#94a3b8').stroke().undash();
    y += 6;
  };
  const kv = (label, value, { bold = false, size = 8 } = {}) => {
    doc.font('Helvetica').fontSize(size).fillColor(MUTED).text(label, MINI_M, y, { width: 70 });
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(size).fillColor(INK);
    doc.text(value, MINI_M + 70, y, { width: W - 70, align: 'right' });
    y = Math.max(doc.y, y + size + 2) + 3;
  };

  center(COMPANY.toUpperCase(), 13, 'Helvetica-Bold', ACCENT);
  center(event?.name || 'Event sale', 9, 'Helvetica-Bold');
  if (event?.venue) center(event.venue, 7.5, 'Helvetica', MUTED);
  rule();

  kv('Bill No', bill.billLabel || bill.ref, { bold: true });
  kv('Date', formatDateTime(bill.verifiedAt || bill.createdAt));
  kv('Customer', bill.customerName);
  kv('Mobile', `+91 ${bill.customerMobile}`);
  rule();

  for (const l of lines) {
    doc.font('Helvetica-Bold').fontSize(8).fillColor(INK).text(l.name, MINI_M, y, { width: W, ellipsis: true, height: 10 });
    y += 11;
    doc.font('Helvetica').fontSize(8).fillColor(MUTED).text(`${l.quantity} × ${amountOnly(l.price)}`, MINI_M + 8, y, { width: W - 90 });
    doc.fillColor(INK).text(amountOnly(l.amount), MINI_M + W - 90, y, { width: 90, align: 'right' });
    y += 14;
  }
  rule();

  kv('Total qty', String(bill.totalQuantity));
  kv('TOTAL', formatINR(bill.totalAmount), { bold: true, size: 11 });
  kv('Paid by', bill.paymentMode === 'upi' ? 'UPI' : 'Cash', { bold: true });
  if (bill.upiRef) kv('UPI ref', bill.upiRef);
  kv('Billed by', bill.billerName || '—');
  rule();

  doc.font('Helvetica').fontSize(7).fillColor(MUTED);
  doc.text(
    bill.paymentMode === 'upi'
      ? 'Paid by UPI — the payment photo is on file with this bill.'
      : `Confirmed by the customer with the OTP sent to +91 ••••••${String(bill.customerMobile).slice(-4)}.`,
    MINI_M,
    y,
    { width: W, align: 'center' }
  );
  y = doc.y + 6;
  center('Thank you!', 9, 'Helvetica-Bold', ACCENT);

  return docToBuffer(doc);
}

function evTableHeader(doc, y, cols) {
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor(MUTED);
  for (const c of cols) doc.text(c.label.toUpperCase(), c.x, y, { width: c.w, align: c.align || 'left' });
  doc.moveTo(50, y + 12).lineTo(545, y + 12).strokeColor(LINE).stroke();
  return y + 17;
}

/** New page (repeating the table header) when the next `needed` points won't fit. */
function evSpace(doc, y, needed, cols) {
  if (y <= 770 - needed) return y;
  footer(doc);
  doc.addPage();
  return cols ? evTableHeader(doc, 60, cols) : 60;
}

function evRow(doc, y, cols, values, { bold = false, size = 8.5, colors = {} } = {}) {
  cols.forEach((c, i) => {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(size).fillColor(colors[i] || INK);
    doc.text(String(values[i] ?? ''), c.x, y, { width: c.w, align: c.align || 'left', ellipsis: true, height: size + 3 });
  });
  return y + size + 7;
}

function evSection(doc, y, title, note) {
  y = evSpace(doc, y, 110);
  doc.font('Helvetica-Bold').fontSize(11).fillColor(INK).text(title, 50, y);
  y = doc.y + 2;
  if (note) {
    doc.font('Helvetica').fontSize(8).fillColor(MUTED).text(note, 50, y, { width: 495 });
    y = doc.y + 2;
  }
  return y + 6;
}

function eventPeriod(event) {
  if (event.startDate && event.endDate && event.startDate !== event.endDate) return `${event.startDate} to ${event.endDate}`;
  return event.startDate || event.endDate || '';
}

/**
 * Whole-event report: sales summary, item-wise stock reconciliation,
 * receiver-wise and day-wise cash/UPI, every verified bill, the stock ledger.
 * report = buildEventReport() output.
 */
export function eventReportPdf(report) {
  const { event, totals } = report;
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  const sub = [event.venue, eventPeriod(event), event.status === 'closed' ? 'Closed' : 'Open', `Generated ${formatDateTime(report.generatedAt)} IST`]
    .filter(Boolean)
    .join(' • ');
  header(doc, `Event Report — ${event.name}`, sub);

  // Summary band
  let y = doc.y + 4;
  doc.roundedRect(50, y, 495, 64, 6).fillAndStroke(ACCENT_BG, ACCENT_BORDER);
  doc.fillColor(MUTED).font('Helvetica').fontSize(8).text('TOTAL SALES (VERIFIED BILLS)', 66, y + 10);
  doc.fillColor(ACCENT).font('Helvetica-Bold').fontSize(18).text(formatINR(totals.amount), 66, y + 22);
  doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text(`${totals.bills} bills • ${totals.quantity} units sold`, 66, y + 46);
  const money = (label, amount, count, x) => {
    doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(label, x, y + 10);
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(12).text(formatINR(amount), x, y + 22, { width: 115 });
    doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(`${count} bill${count === 1 ? '' : 's'}`, x, y + 40);
  };
  money('CASH', totals.cash, totals.cashBills, 300);
  money('UPI', totals.upi, totals.upiBills, 425);
  y += 80;

  // Item-wise stock & sales
  const itemCols = [
    { label: 'Item', x: 50, w: 140 },
    { label: 'Rate', x: 190, w: 60, align: 'right' },
    { label: 'Stock in', x: 250, w: 50, align: 'right' },
    { label: 'Out', x: 300, w: 40, align: 'right' },
    { label: 'Sold', x: 340, w: 45, align: 'right' },
    { label: 'Remaining', x: 385, w: 60, align: 'right' },
    { label: 'Sales', x: 445, w: 100, align: 'right' },
  ];
  y = evSection(doc, y, 'Item-wise stock & sales', 'Remaining = stock in - stock out - sold on verified bills. A negative figure means more was billed than recorded as received.');
  y = evTableHeader(doc, y, itemCols);
  for (const i of report.items) {
    y = evSpace(doc, y, 30, itemCols);
    y = evRow(
      doc,
      y,
      itemCols,
      [i.isActive ? i.name : `${i.name} (retired)`, amountOnly(i.price), i.stockIn, i.stockOut, i.sold, i.remaining, formatINR(i.salesAmount)],
      { colors: { 5: i.remaining < 0 ? '#dc2626' : INK } }
    );
  }
  y = evSpace(doc, y, 30, itemCols);
  doc.moveTo(50, y - 2).lineTo(545, y - 2).strokeColor(LINE).stroke();
  y = evRow(doc, y + 3, itemCols, ['Total', '', report.stock.stockIn, report.stock.stockOut, totals.quantity, report.stock.remaining, formatINR(totals.amount)], { bold: true });
  y += 10;

  // Collector-wise and day-wise cash / UPI
  const splitCols = (first) => [
    { label: first, x: 50, w: 165 },
    { label: 'Bills', x: 215, w: 45, align: 'right' },
    { label: 'Qty', x: 260, w: 50, align: 'right' },
    { label: 'Cash', x: 310, w: 80, align: 'right' },
    { label: 'UPI', x: 390, w: 75, align: 'right' },
    { label: 'Total', x: 465, w: 80, align: 'right' },
  ];
  const splitTable = (title, note, cols, rows, labelOf) => {
    y = evSection(doc, y, title, note);
    y = evTableHeader(doc, y, cols);
    if (!rows.length) {
      doc.font('Helvetica').fontSize(8.5).fillColor(MUTED).text('No verified bills yet.', 50, y);
      y += 18;
      return;
    }
    for (const r of rows) {
      y = evSpace(doc, y, 30, cols);
      y = evRow(doc, y, cols, [labelOf(r), r.bills, r.quantity, amountOnly(r.cash), amountOnly(r.upi), amountOnly(r.amount)]);
    }
    y = evSpace(doc, y, 30, cols);
    doc.moveTo(50, y - 2).lineTo(545, y - 2).strokeColor(LINE).stroke();
    y = evRow(doc, y + 3, cols, ['Total', totals.bills, totals.quantity, amountOnly(totals.cash), amountOnly(totals.upi), amountOnly(totals.amount)], { bold: true });
    y += 10;
  };
  splitTable('Collector-wise', 'Cash column = cash each collector should be holding from this event.', splitCols('Billed by'), report.byBiller, (r) => r.name);
  splitTable('Day-wise', null, splitCols('Date'), report.days, (d) => d.label);

  // Every verified bill
  const billCols = [
    { label: 'Bill', x: 50, w: 36 },
    { label: 'Date & time', x: 86, w: 92 },
    { label: 'Customer', x: 178, w: 112 },
    { label: 'Items', x: 290, w: 120 },
    { label: 'Paid by', x: 410, w: 60 },
    { label: 'Amount', x: 470, w: 75, align: 'right' },
  ];
  const muted = Object.fromEntries(billCols.map((_, i) => [i, MUTED]));
  y = evSection(doc, y, `Bills (${report.bills.length})`, 'Confirmed bills only — cash bills by an OTP sent to the customer, UPI bills by the stored payment photo.');
  y = evTableHeader(doc, y, billCols);
  for (const b of report.bills) {
    y = evSpace(doc, y, 36, billCols);
    evRow(doc, y, billCols, [b.billLabel, formatDateTime(b.date), b.customerName, b.itemsLabel, b.paymentMode === 'upi' ? 'UPI' : 'Cash', amountOnly(b.totalAmount)]);
    evRow(
      doc,
      y + 11,
      billCols,
      ['', '', `+91 ${b.customerMobile}`, `by ${b.billerName}`, b.paymentMode === 'upi' ? b.upiRef || (b.hasScreenshot ? 'photo' : '') : '', ''],
      { size: 7, colors: muted }
    );
    y += 26;
  }
  y = evSpace(doc, y, 30, billCols);
  doc.moveTo(300, y).lineTo(545, y).strokeColor(INK).stroke();
  y += 6;
  doc.font('Helvetica-Bold').fontSize(10).fillColor(ACCENT);
  doc.text('TOTAL SALES', 250, y, { width: 190, align: 'right' });
  doc.text(formatINR(totals.amount), 445, y, { width: 100, align: 'right' });
  y += 24;

  const other = Object.entries(report.statusCounts || {}).filter(([s]) => s !== 'verified');
  if (other.length) {
    y = evSpace(doc, y, 30);
    doc.font('Helvetica').fontSize(8).fillColor(MUTED);
    doc.text(
      `Not counted (never verified by customer OTP): ${other.map(([s, v]) => `${s.replace('_', ' ')} ${v.count} (${formatINR(v.amount)})`).join(' • ')}`,
      50,
      y,
      { width: 495 }
    );
    y = doc.y + 12;
  }

  // Stock ledger
  const ledgerCols = [
    { label: 'Date & time', x: 50, w: 95 },
    { label: 'Item', x: 145, w: 130 },
    { label: 'Type', x: 275, w: 40 },
    { label: 'Qty', x: 315, w: 40, align: 'right' },
    { label: 'Entered by', x: 365, w: 80 },
    { label: 'Note', x: 445, w: 100 },
  ];
  y = evSection(doc, y, `Stock ledger (${report.stockEntries.length})`, 'Entered by the event stock keeper. Append-only — corrections appear as separate entries.');
  y = evTableHeader(doc, y, ledgerCols);
  if (!report.stockEntries.length) {
    doc.font('Helvetica').fontSize(8.5).fillColor(MUTED).text('No stock entries recorded.', 50, y);
  }
  for (const e of report.stockEntries) {
    const tone = e.kind === 'in' ? ACCENT : '#b45309';
    y = evSpace(doc, y, 30, ledgerCols);
    y = evRow(
      doc,
      y,
      ledgerCols,
      [formatDateTime(e.date), e.itemName, e.kind === 'in' ? 'In' : 'Out', e.kind === 'in' ? e.quantity : -e.quantity, e.enteredByName, e.note || '—'],
      { colors: { 2: tone, 3: tone } }
    );
  }

  footer(doc);
  return docToBuffer(doc);
}

/**
 * Archive of UPI payment screenshots, two side by side per page (phone
 * screenshots are tall, so tall columns keep the UTR legible in print), each
 * captioned with its bill. bills = billRow()s with a screenshot;
 * loadBatch(ids) resolves to a Map of bill id → { data, contentType, sha256 },
 * fetched a few at a time so the images never all sit in memory at once.
 */
export async function eventScreenshotsPdf({ event, subtitle, bills, loadBatch, note }) {
  const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
  header(doc, `UPI Payment Photos — ${event.name}`, subtitle);
  let y = doc.y + 4;
  if (note) {
    doc.font('Helvetica').fontSize(8.5).fillColor(MUTED).text(note, 50, y, { width: 495 });
    y = doc.y + 8;
  }
  if (!bills.length) {
    doc.font('Helvetica').fontSize(10).fillColor(MUTED).text('No UPI payment photos in this period.', 50, y);
  }

  const COL_W = 240;
  const GAP = 15;
  const CAPTION_H = 48;
  const BOX_H = 550;
  let col = 0;
  for (let i = 0; i < bills.length; i += 10) {
    const batch = bills.slice(i, i + 10);
    const images = await loadBatch(batch.map((b) => b.id));
    for (const b of batch) {
      if (col === 0 && y + CAPTION_H + BOX_H > 770) {
        footer(doc);
        doc.addPage();
        y = 60;
      }
      const x = 50 + col * (COL_W + GAP);
      const img = images.get(String(b.id));
      const line = (text, dy, font, size, color) => {
        doc.font(font).fontSize(size).fillColor(color);
        doc.text(text, x, y + dy, { width: COL_W, ellipsis: true, height: size + 3 });
      };
      line(`Bill ${b.billLabel || b.ref} • ${formatDateTime(b.date)}`, 0, 'Helvetica-Bold', 8.5, INK);
      line(`${b.customerName} • +91 ${b.customerMobile}`, 12, 'Helvetica', 8, INK);
      line(`${formatINR(b.totalAmount)} • UPI ref ${b.upiRef || '—'}`, 23, 'Helvetica', 7.5, MUTED);
      line(`Billed by ${b.billerName}${img ? ` • SHA-256 ${img.sha256.slice(0, 12)}…` : ''}`, 33, 'Helvetica', 7, MUTED);

      const top = y + CAPTION_H;
      doc.roundedRect(x, top, COL_W, BOX_H, 4).strokeColor(LINE).stroke();
      let drawn = false;
      if (img && (img.contentType === 'image/jpeg' || img.contentType === 'image/png')) {
        try {
          doc.image(img.data, x + 4, top + 4, { fit: [COL_W - 8, BOX_H - 8], align: 'center', valign: 'center' });
          drawn = true;
        } catch (err) {
          console.error(`[pdf] screenshot for bill ${b.ref} could not be embedded:`, err.message);
        }
      }
      if (!drawn) {
        doc.font('Helvetica').fontSize(9).fillColor(MUTED);
        doc.text(
          img ? 'Photo is stored, but in a format the PDF cannot embed — view it in the app.' : 'Photo not found.',
          x + 12,
          top + BOX_H / 2 - 12,
          { width: COL_W - 24, align: 'center' }
        );
      }

      col += 1;
      if (col === 2) {
        col = 0;
        y = top + BOX_H + 16;
      }
    }
  }

  footer(doc);
  return docToBuffer(doc);
}
